package com.craftinginterpreters.lox;

enum TokenType{
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, 
    COMMA, DOT, DASH, PLUS, SEMICOLON, SLASH, STAR, //
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_GREATER,
    LESS, LESS_EQUAL, //
    IDENTIFIER, STRING, NUMBER. //
    ADD, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR,
    PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE, //
    EOF
      
}